function ModelEstimation1D(data, actualDistribution, label)

[ans_sigma, ans_mu, ans_lambda] = parametricEstimator1D(data);

estimate_a_gauss = gaussian(ans_mu, ans_sigma^0.5);
estimate_a_exp = exponential(ans_lambda);

PlotDistributions(estimate_a_gauss, actualDistribution,...
    0:0.01:10,...
    "Estimate of Gaussian using Gaussian Parametric Estimate for Dataset "...
    + label)
PlotDistributions(estimate_a_exp, actualDistribution,...
    0:0.01:10,...
    "Estimate of Gaussian using Exponential Parametric Estimate for Dataset "...
    + label)

end

